# Generated by Django 3.2.6 on 2021-09-30 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='time_range',
        ),
        migrations.AddField(
            model_name='shift',
            name='description',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='休憩時間'),
        ),
    ]
